### ISSUE TITLE
Making requests when getting updates

### ISSUE THREAD

**Issue by 9px** [datamachine/twx.botapi#10]
hi. telegram [recently](https://core.telegram.org/bots/api#making-requests-when-getting-updates) add an ability to perform a request to the telegram Bot API while sending an answer to the webhook.
can you do a simple implement of this feature in your bot?

**Comment by FichteFoll** [comment]
Afaic this is about making requests in the answer to the webhook request. twx.botapi is only for long polling updates and not for webhooks.

Edit: And making requests, of course.

**Comment by fopina** [comment]
@9px twx.botapi can be used for webhooks (I use it always with webhooks) but it doesn't implement the webserver itself. twx.botapi already implements the set_webhook
- so you setup your bot instance
- start your WSGI app (with at least one route defined - the one that receives updates)

Normally, it can look something like this (in Bottle):

```
app = Bottle()
bot = TelegramBot(...)

@app.route('/update/<token>', method='POST')
def update(token):
    if token != bot.token:
        abort(404, 'Not found: \'/update/%s\'' % token)

    u = Update.from_dict(request.json)
    .... (do something with update) ...
    bot.send_message(u.message.chat.id, '123')
    return None
```

To use the webhook response, twx.botapi is not very friendly but can you can still achieve it changing the route as such:

```
    ...
    u = Update.from_dict(request.json)
    .... (do something with update) ...
    # CHANGE STARTS HERE, using botapi.send_message instead of TelegramBot().send_message to avoid implicit .run()
    m = send_message(u.message.chat.id, '123', token=bot.token)
    m.params['method'] = m.api_method
    # return the dict() instead of None. Bottle automatically encodes dict()s as JSON and sets proper content-type
    return m.params
```

I'm actually working on implementing this on my [tgbotplug](https://github.com/fopina/tgbotplug) library which uses twx.botapi for API calls (though having some issues with design trying to keep it friendly :))
