### ISSUE TITLE
Old-style classes

### ISSUE THREAD

**Issue by jlmadurga** [datamachine/twx.botapi#15]
Is there any reason to use _old-style_ classes? I was trying to inherit from `TelegramBot` and found the `super` issue: `TypeError: must be type, not classobj` related to.
I fixed not using super but I think it is recommended to use _new-style_.

**Comment by FichteFoll** [comment]
~~You must use Python 3 anyway, afaik.~~

Actually, according to the readme it supports 2.7 too, but ... I wouldn't be too sure about that. If you use 3 you're definitely on the safe side though.

**Comment by jlmadurga** [comment]
I am using 2.7 and it works fine at least as far I have tested. Receiving and sending text messages.

**Comment by FichteFoll** [comment]
Well, it's good practise to always inherit from `object` anyway, for this kind of backwards compatability.
