### ISSUE TITLE
Build with error via pip

### ISSUE THREAD

**Issue by xarpov** [datamachine/twx.botapi#26]
macOS 10.12.2

╭  [16:21:30] aleksandr.momot@mac [~/Git/bot] (master)
╰  $ (.env) python --version
Python 3.5.2

> pip install twx.botapi
`Running setup.py bdist_wheel for twx.botapi ... error
  Complete output from command /Users/aleksandr.momot/Git/flatter.bot/.env/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/yl/9ptm06d121q2n8xxdwdvf3fdtd6v_h/T/pip-build-rp4urqrx/twx.botapi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/yl/9ptm06d121q2n8xxdwdvf3fdtd6v_h/T/tmpb_r66w1tpip-wheel- --python-tag cp35:
  https://github.com/datamachine/twx.botapi/archive/3.1.1.zip
  ['requests']
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/twx
  copying twx/__init__.py -> build/lib/twx
  creating build/lib/twx/botapi
  copying twx/botapi/__init__.py -> build/lib/twx/botapi
  copying twx/botapi/botapi.py -> build/lib/twx/botapi
  installing to build/bdist.macosx-10.11-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.macosx-10.11-x86_64
  creating build/bdist.macosx-10.11-x86_64/wheel
  creating build/bdist.macosx-10.11-x86_64/wheel/twx
  copying build/lib/twx/__init__.py -> build/bdist.macosx-10.11-x86_64/wheel/twx
  creating build/bdist.macosx-10.11-x86_64/wheel/twx/botapi
  copying build/lib/twx/botapi/__init__.py -> build/bdist.macosx-10.11-x86_64/wheel/twx/botapi
  copying build/lib/twx/botapi/botapi.py -> build/bdist.macosx-10.11-x86_64/wheel/twx/botapi
  running install_egg_info
  running egg_info
  writing twx.botapi.egg-info/PKG-INFO
  writing top-level names to twx.botapi.egg-info/top_level.txt
  writing dependency_links to twx.botapi.egg-info/dependency_links.txt
  writing requirements to twx.botapi.egg-info/requires.txt
  reading manifest file 'twx.botapi.egg-info/SOURCES.txt'
  writing manifest file 'twx.botapi.egg-info/SOURCES.txt'
  Copying twx.botapi.egg-info to build/bdist.macosx-10.11-x86_64/wheel/twx.botapi-3.1.1-py3.5.egg-info
  running install_scripts
  error: [Errno 2] No such file or directory: 'LICENSE'

  ----------------------------------------
  Failed building wheel for twx.botapi
  Running setup.py clean for twx.botapi`

But the package is actually installed to python lib.

**Comment by Surye** [comment]
Fix pulled in, thanks.
