### ISSUE TITLE
send_voice isn't able to add a caption to voice messages

### ISSUE THREAD

**Issue by d-Rickyy-b** [datamachine/twx.botapi#28]
There is no caption field

Compare: [twx.botapi](http://pythonhosted.org/twx.botapi/twx/botapi/botapi.html#send-voice) and [Telegram API](https://core.telegram.org/bots/api#sendvoice)
___
[send_video](http://pythonhosted.org/twx.botapi/twx/botapi/botapi.html#send-video) is able to add a caption to the video

**Comment by Surye** [comment]
send_audio does have caption, this is a documentation issue to be fixed in the new release.
