### ISSUE TITLE
cannot import name helpers

### ISSUE THREAD

**Issue by hathucphuc** [datamachine/twx.botapi#31]
I cannot send alert messages to telegram by Nagios.
I have already installed python34 and twx.botapi-3.6 successfully
When run telegram_nagios.py I get error as blow : 
![image](https://user-images.githubusercontent.com/39231457/39969400-3bea37d4-5705-11e8-8817-c0282f1c5ec1.png)

**Comment by Surye** [comment]
Thank you for opening up an issue, I will get a fix deployed for this
today.

>
